---
abstract: 'A less opinionated, minimal featured way to serve static files.'
author:
  - 'John Napiorkowski <jjnapiork@cpan.org>'
build_requires:
  Test::Most: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catalyst-Plugin-ServeFile
requires:
  Catalyst: '5.90060'
  File::Spec: '0'
  HTTP::Date: '6.02'
  Moo: '2.003004'
  Plack: '1.0047'
resources:
  bugtracker: https://github.com/jjn1056/Catalyst-Plugin-ServeFile/issues
  homepage: https://github.com/jjn1056/Catalyst-Plugin-ServeFile
  repository: https://github.com/jjn1056/Catalyst-Plugin-ServeFile.git
version: '0.001'
x_serialization_backend: 'YAML::Tiny version 1.70'
